# .github/mergify.yml
pull_request_rules:
  - name: "Auto approve and merge PR from master to azure-pipelines"
    conditions:
      - "base=azure-pipelines"
      - "head=sync-master-to-azure-pipelines"
    actions:
      merge:
        method: "squash"
