# .github/mergify.yml
pull_request_rules:
  - name: "Auto approve and merge PR from master to azure-pipelines"
    conditions:
      - "base=azure-pipelines"   # Target branch is azure-pipelines
      - "head=master"             # Source branch is master
    actions:
      merge:
        method: "squash"          # Merge method (can be "merge", "squash", or "rebase")
