#!/usr/bin/python 

import os, time

try:
    query = os.environ['QUERY_STRING']
    ip    = os.environ['REMOTE_ADDR']
    date = '%d.%02d.%02d'   % time.localtime( time.time() )[0:3]
    time = '%02d:%02d:%02d' % time.localtime( time.time() )[3:6]
except Exception, error:
    print('Content-type: text/html\n\n')
    print('Fatal Error:', error)
else:
    print('Location: http://aros.sourceforge.net/downloads/nightly/' + query + '\n\n')
