#!/usr/bin/python

import os, os.path, re, glob, stat, string, cgi
from color import *
from ConfigParser import ConfigParser

print '''Content-Type: text/html\n\n'''

## Parse arguments ###########################################################

args = cgi.FieldStorage()

if args.has_key( 'testpage' ):
    tstpage = args['testpage'].value
else:
    tstpage = ''

activepage = ''
unittestroot  = '../unittests/'

## Process files #############################################################

oldcwd = os.getcwd()

results = {}

for file in os.listdir( unittestroot):
        results.append( file )
        if tstpage != '':
            if tstpage == file:
                activepage = file
        elif activepage == '':
            activepage = file

## Output HTML ###############################################################

print '''
<table style="width: 100%; text-align: justify; margin-left: auto; margin-right: auto; background: url(/images/bgcolormain.png);" border="0" cellpadding="1" cellspacing="1">
   <tr>
      <td>
         <h1>Unit Test Results<br><img style="width: 238px; height: 2px;" alt="spacer" src="/images/sidespacer.png"></h1>
      </td>
    </tr>
''' % vars()

print '''
   <tr>
      <td>
        <select name="unittests" id="unittests">
'''
for result in results:
    print '''
            <option value="%(result)s">%(result)s</option>
    ''' % result

print '''
        </select>
      </td>
    </tr>
'''

print '''
   <tr>
      <td>
         <object width="100%" height="400" data="" type="text/html"></object>
      </td>
   </tr>
</table>
'''
