name: Auto-Approve and Merge Sync PR

on:
  workflow_run:
    workflows: ["Create PR from master to azure-pipelines"]
    types:
      - completed

jobs:
  auto-approve-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install -g @actions/github-script@5
          gh version

      - name: Get PR number from workflow run
        id: pr
        run: |
          PR_URL=$(gh pr list --repo ${{ github.repository }} --head auto-sync-master-to-azure-pipelines --base azure-pipelines --json number --jq '.[0].number')
          if [ -z "$PR_URL" ]; then
            echo "No open PR found"
            exit 1
          fi
          echo "pr_number=$PR_URL" >> $GITHUB_OUTPUT

      - name: Auto approve the PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pr_number }}

      - name: Auto merge the PR
        run: |
          gh pr merge ${{ steps.pr.outputs.pr_number }} --repo ${{ github.repository }} --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
