name: Auto-Approve and Merge PR from master

on:
  workflow_run:
    workflows: ["Create PR from master to azure-pipelines"]  # Ensure this triggers after the PR is created
    types:
      - completed

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get PR number
        id: pr_number
        run: |
          echo "PR_NUMBER=$(curl -s \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            'https://api.github.com/repos/aros-development-team/documentation/pulls' \
            | jq '.[0].number')" >> $GITHUB_ENV
          echo "PR number: $PR_NUMBER"

      - name: Approve PR
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event":"APPROVE"}' \
            "https://api.github.com/repos/aros-development-team/documentation/pulls/${{ env.PR_NUMBER }}/reviews"
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}

      - name: Merge the PR
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"commit_title": "Merge PR", "merge_method": "merge"}' \
            "https://api.github.com/repos/aros-development-team/documentation/pulls/${{ env.PR_NUMBER }}/merge"
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}

