name: Auto-Approve and Merge PR from master

on:
  workflow_run:
    workflows: ["Create PR from master to azure-pipelines"]  # adjust to your PR creation workflow name
    types:
      - completed

jobs:
  auto-approve-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests && github.event.workflow_run.pull_requests[0] }}
    runs-on: ubuntu-latest

    steps:
      - name: Auto approve the PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}

      - name: Auto merge the PR
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
