name: Auto-Approve and Merge PR from master

on:
  workflow_run:
    workflows: ["Create PR from master to azure-pipelines"]
    types:
      - completed

jobs:
  auto-approve-and-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo (needed for some actions)
        uses: actions/checkout@v3

      - name: Auto approve the PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}

      - name: Auto merge the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.workflow_run.pull_requests[0].number }};
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "squash"
            });
