name: Auto-Approve and Merge PR from master

on:
  workflow_run:
    workflows: ["Create PR from master to azure-pipelines"]  # The name of your PR creation workflow
    types:
      - completed

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get PR number
        id: pr_info
        run: |
          pr_response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.event.workflow_run.head_commit.id }}")

          # Debugging: Output the response to check if it's correct
          echo "PR Response: $pr_response"

          # Check if PR exists
          if [[ "$pr_response" == "[]" ]]; then
            echo "No PR found. Exiting."
            exit 1
          fi

          pr_number=$(echo "$pr_response" | jq '.[0].number')

          # Debugging: Check if PR number was extracted
          if [[ -z "$pr_number" ]]; then
            echo "Error: PR number extraction failed."
            exit 1
          fi

          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "PR Number: $pr_number"  # Print the PR number for debugging

      - name: Auto approve the PR via API
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"event":"APPROVE"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/reviews"

      - name: Auto merge the PR
        uses: pascalgn/automerge-action@v0.15.3
        with:
          pull-request-number: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN is used for merging
